### ISSUE TITLE
关于PersonaChat数据集的问题

### ISSUE THREAD

**Issue by 27182812** [chengjl19/PAL#3]
作者您好，不知道能否提供你们实验室的PersonaChat数据集。因为我convai2获取的数据集里没有test。我看process_bart_df.py代码里有test，你们是自己划分的吗？

**Comment by chengjl19** [comment]
We didn't split it. I really forget where I download it, but I upload it and here is the url: https://drive.google.com/drive/folders/1-lnO2xi9YLr82VdcF5oVlQClHsRnn9EP?usp=sharing

**Comment by 27182812** [comment]
Thank you vey much!
