### ISSUE TITLE
Hello, can I ask you how to compute cos similarity between persona and response?

### ISSUE THREAD

**Issue by zeddyuu** [chengjl19/PAL#5]
Hello,
I have read your paper and would like to know how to calculate the cosine similarity for persona and response.
I have reviewed /RUN/get_gen_sim_cos.sh in your code and would like to know how the input file is generated.
Thanks!

**Comment by chengjl19** [comment]
You can use simcse to calculate this, translating the text to embedding and then calculate the cos similarity

**Comment by chengjl19** [comment]
refer to this: https://github.com/princeton-nlp/SimCSE
