### ISSUE TITLE
Experiment Results

### ISSUE THREAD

**Issue by Bat-Reality** [chengjl19/PAL#6]
I used the code provided on github, but I can't get the same results, especially the metric DISTINCT. Is there anything I haven't adjusted?
| Model | ACC | PPL | B-2 | B-4 | D-1 | D-2 | R-L |
| - | - | - | - | - | - | - | - |
| PAL | 34.51 | 15.92 | 8.75 | 2.66 | 5.00 | 30.27 | 18.06 |
| PAL* | 29.70 | 14.60 | 8.38 | 2.40 | 3.59 | 19.66 | 17.16 |
| PAL* | 30.84 | 15.03 | 8.24 | 2.45 | 3.87 | 20.93 | 17.18 |

**Comment by chengjl19** [comment]
Are you sure the ppl is 115.03, maybe there are some bugs? And the distinct is really strange, I don't know which epoch you used, maybe you can try different epochs.

**Comment by Bat-Reality** [comment]
The ppl is 15.03. I'm sorry for writing wrong ppl. I train for 10 epochs, and PPL generally reaches the lowest in epoch 3. I choose the checkpoint here for inference.

**Comment by chengjl19** [comment]
I see, you can try other epochs, our results show a significant gap between different epochs, especially when epoch3 reaches the lowest loss, the model may not be fully trained.

**Comment by Bat-Reality** [comment]
Thank you very much for your advice, it's very useful.
