### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by githubxuc** [chengjl19/PAL#7]
作者您好，最近攻读了您的论文，对我真的很有启发，接下来是想跑一下您的代码的，但发现里面并没有环境配置的说明，如果方便的话，作者可以发一份环境配置的说明给我吗？不胜感激！

**Comment by chengjl19** [comment]
感谢对我们工作的关注，您可以完全参考这里的环境配置：https://github.com/thu-coai/Emotional-Support-Conversation/blob/main/codes_zcj/env.yml
